### ISSUE TITLE
Standardize output format

### ISSUE THREAD

**Issue by fulldecent** [mcandre/cowl#5]
Hello, would this project be interested in a PR that make output follow a standardized format, namely https://github.com/fulldecent/structured-acceptance-test

**Comment by mcandre** [comment]
you are ON it

**Comment by ilyalyo** [comment]
Added a PR: https://github.com/mcandre/cowl/pull/7

**Comment by mcandre** [comment]
Cheers!

Pro GitHub tip: If you reference an issue from the PR, such as saying

> closes #5

in the commit or description of the PR, then GitHub automatically links the PR and issue together for you.

**Comment by ilyalyo** [comment]
thanks) will use it

**Comment by fulldecent** [comment]
@ilyalyo Please add a link to cowl at https://github.com/fulldecent/structured-acceptance-test/blob/master/README.md
